//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunilMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANDIDATO
    {
        public CANDIDATO()
        {
            this.CANDIDATOVAGA = new HashSet<CANDIDATOVAGA>();
        }
    
        public int CANID { get; set; }
        public string CANNOME { get; set; }
        public string CANFORMACAO { get; set; }
    
        public virtual ICollection<CANDIDATOVAGA> CANDIDATOVAGA { get; set; }
    }
}
