//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunilMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANDIDATOVAGA
    {
        public int CANID { get; set; }
        public int VAIID { get; set; }
        public System.DateTime CAVDATACADASTRO { get; set; }
        public string CAVSTATUSCANDIDATURA { get; set; }
    
        public virtual CANDIDATO CANDIDATO { get; set; }
        public virtual VAGA VAGA { get; set; }
    }
}
