//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunilMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoCandidatoVaga
    {
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public string Vaga { get; set; }
        public System.DateTime DataDeCadastro { get; set; }
        public string Situacao { get; set; }
        public int CodigoV { get; set; }
    }
}
